"use client"

import { Inter } from "next/font/google";
import { ExperimentProvider } from "@/context/ExperimentContext";
import { QueryClient, QueryClientProvider } from "react-query";
import "./globals.css";
import NetworkObserver from "@/components/NetworkObserver";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: 2,
      refetchOnWindowFocus: false,
      staleTime: 1000 * 60, // 1 min
    },
  },
});

const metadata = {
  title: "Gen AI",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <QueryClientProvider client={queryClient}>
          <ExperimentProvider>
            <Toaster />
            {children}
          </ExperimentProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
